### ISSUE TITLE
cloudscale api token is mandatory for local keepalived

### ISSUE THREAD

**Issue by tuxpeople** [puzzle/ansible-rancher#18]
When I use `keepalived_setup_env=local`, keepalive deployment fails:
```
TASK [rancher_keepalived : Create IP Failover DaemonSets for Internal IP] *********************************************************************************************************************************************
fatal: [rancher_mycluster]: FAILED! =>
  msg: |-
    The task includes an option with an undefined variable. The error was: 'cloudscale_api_token' is undefined

    The error appears to be in '/path/git/ansible-rancher/roles/rancher_keepalived/tasks/configure-keepalived.yml': line 105, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.

    The offending line appears to be:


    - name: Create IP Failover DaemonSets for Internal IP
      ^ here
```

As soon as i set the token to a random string (eg. `cloudscale_api_token="n/a"`) it works. It does not use the string at all, but it requires it.

**Comment by PhilipSchmid** [comment]
Hi @tuxpeople,

Thanks for reporting this issue! It should now be fixed since I removed the default value `{{ cloudscale_api_token }}` from the `keepalived_cloudscale_api_token` configuration variable. If this keepalived Ansible role is used for a Cloudscale setup this reassignment should be done inside the `host_vars`.

Regards,
Philip
