### ISSUE TITLE
Question: K8S roles

### ISSUE THREAD

**Issue by tuxpeople** [puzzle/ansible-rancher#20]
I've a question regarding the k8s roles assigned based on the inventory groups.

Given this sample inventory excerpt:
```
[mycluster_master]
node01
node02
node03

[mycluster_worker]
node01
node02
node03
```

All the nodes only get the worker role assigned. It completely ignores that they should (?) inherit the other two roles from the mycluster_master group. I solved this by adding all three roles to the mycluster_worker group.

I'm fully aware that this is 

a) not the best idea of building a Kubernetes cluster
b) not supported by Rancher

but it's useful for testing and/or development scenarios. My question is: is this a issue of how this roles here are working? Or is it the behavior of Ansible? I assum the later, but I'm wondering.

**Comment by PhilipSchmid** [comment]
Hi @tuxpeople,

A host should only be assigned to a single group.

We use this Ansible roles to install Rancher clusters in a wide variety of scenarios. For local/dev setups you are totally right, it would make 100% sense to assign the role exclusively depending on the hosts group assignment (`..._master`/`..._worker`). In real world use cases we also already had scenarios where we needed mix roles in different ways. Therefore we chose to include a configuration option in form of the `k8s_roles` group variable to gain this flexibility.

I usually test the local setup using this setup here: https://github.com/PhilipSchmid/vagrant-rancher-playground (the automated setup using Ansible variant).
For efficiency purposes I usually also deploy all roles to all nodes since my system is a bit limited regarding cpu/memory resources and therefore I can't really run a dedicated 3 node HA control plane cluster etc.. 

- My inventory in this case only uses two groups - one for the Rancher control plane cluster und one for the custom K8s cluster: https://github.com/PhilipSchmid/vagrant-rancher-playground/blob/6c85074c3c1445dad25b539cd582aebc7c34b53f/ansible_setup/ansible-rancher/inventories/site#L16-L24 
- I then assign the roles via `group_vars`: https://github.com/PhilipSchmid/vagrant-rancher-playground/tree/master/ansible_setup/ansible-rancher/inventories/group_vars

I would recommend you to do the same for your testing/development environment. I hope this answers your question. If not, please feel free to ask additional questions. Thanks.

Regards,
Philip

**Comment by PhilipSchmid** [comment]
Here is the regarding part: `... {% for role in hostvars[item]['k8s_roles'] %} --{{ role }}{% endfor %}`

https://github.com/puzzle/ansible-rancher/blob/5c30f04ebea16a450e7071e4db33a3538f8808d7/roles/custom_k8s_cluster/tasks/nodes.yml#L26

Regards,
Philip

**Comment by tuxpeople** [comment]
Got it. Thanks a lot!
