### ISSUE TITLE
Rancher now requires turning off firewalld

### ISSUE THREAD

**Issue by XakV** [puzzle/ansible-rancher#23]
https://rancher.com/docs/rancher/v2.x/en/installation/resources/advanced/firewall/

_We recommend disabling firewalld. For Kubernetes 1.19, firewalld must be turned off._

Would you be interested in a PR if it's only tested against RHEL 7?

**Comment by PhilipSchmid** [comment]
Hi @XakV 

To be honest I currently do not see the exact reason behind Rancher's statement `We recommend disabling firewalld. For Kubernetes 1.19, firewalld must be turned off.` since they also list every single port and when they are opened, it should work fine. Nevertheless, a PR which allows it to enable or disable firewalld via variable would be nice!

Thanks in advance!

Regards,
Philip
